import Head from 'next/head'
import Creator from './Components/Creator'
import Header from "./Components/Header"
import HeroSec from "./Components/HeroSec"

export default function Home() {
  return (
    <>
      <Head>
        <title>Lenspost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./Logo.png" />
      </Head>
      <main className="bg-black">
       <Header />
       <HeroSec />
       <Creator />
      </main>
    </>
  )
}
